# Create users with AmazonS3FullAccess and AdministratorAccess-AWSElasticBeanstalk permissions, download security credentials
# Create S3Bucket: name - "aws-cicd-project"
# Create EB in us-east-1 data-center (N. Virginia region): application name - "aws-cicd-project" and environment name - "Awscicdproject-env"
# Launch GitHub repo with project files
# Come to repo settings -> secrets -> add secrets data from s.1 (aws-access-key-id, aws-secret-access-key)
# Come to repo -> actions -> set up a workflow yourself -> main.yml
# Input code below:

name: CI-CD
env:
  EB_PACKAGE_S3: "aws-cicd-project"
  EB_APP_NAME  : "aws-cicd-project"
  EB_ENVIRONMENT_NAME: "Awscicdproject-env"
  DEPLOY_PACKAGE    : "flask_app_${{github.sha}}.zip"
  AWS_REGION_NAME   : "us-east-1"
  
on:
  push:
    branches:
      - master
      
jobs:
  my_ci_part:
    runs-on: ubuntu-latest
    
    steps:
      - name: Git clone our repo
        uses: actions/checkout@v1  
      
      - name: Create ZIP
        run: zip -r ${{env.DEPLOY_PACKAGE}} ./ -x *.git*
      
      - name: Configure my AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.ACCESS_KEY}}
          aws-secret-access-key: ${{secrets.SECRET_KEY}}
          aws-region: ${{env.AWS_REGION_NAME}}
        
      - name: Copy
        run: aws s3 cp ${{env.DEPLOY_PACKAGE}} s3://${{env.EB_PACKAGE_S3}}/
      
      - name: Print
        run: echo "Finish successfully!"

  my_cd_part:
    runs-on: ubuntu-latest
    needs: [my_ci_part]
    
    steps: 
      
      - name: Configure my AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.ACCESS_KEY}}
          aws-secret-access-key: ${{secrets.SECRET_KEY}}
          aws-region: ${{env.AWS_REGION_NAME}}
          
      - name: Create new EB
        run: |
          aws elasticbeanstalk create-application-version \
          --application-name ${{env.EB_APP_NAME}} \
          --source-bundle S3Bucket="${{env.EB_PACKAGE_S3}}",S3Key="${{env.DEPLOY_PACKAGE}}" \
          --version-label "Ver-${{ github.sha }}" \
          --description "Commit SHA - ${{ github.sha }}"
        
      - name: Deploy new EB
        run: aws elasticbeanstalk update-environment --environment-name ${{env.EB_ENVIRONMENT_NAME}} --version-label "Ver-${{ github.sha }}" 
        
      - name: Print
        run: echo "Finish successfully!"
